### ISSUE TITLE
Possible security vulnerability detected

### ISSUE THREAD

**Issue by daknob** [zer0rest/copypasta#1]
In
https://github.com/zer0rest/copypasta/blob/master/copypasta.sh#L19
and
https://github.com/zer0rest/copypasta/blob/master/copypasta.sh#L37
the code creates a file, by default in `/tmp`, which has, by default, `r`ead permissions for every user. That said, a malicious system user can gain full access to the text / image / data simply by reading it from `/tmp`. This can lead to information disclosure. Moreover, it is unclear whether the files stored in `/tmp` are deleted at any point after the upload, as this does not appear to be in the code itself.

**Comment by zer0rest** [comment]
Hey, 
Regarding the `/tmp` issue, an assumption was made that the`/tmp` folder will be emptied when the computer is restarted since it's a `tmpfs`. As such the files are not deleted, until the host is rebooted. However, I will add logic to delete them, since I think it's a better practice, especially regarding big files.
Regarding the user priviledges issue for `/tmp` that is a valid point. As such a new folder will be added where only **$USER** will have `rw` access.
Thanks.

**Comment by zer0rest** [comment]
Following the previous comment, commit 40f85b6 fixes the issue except from `touch`ing and `chmod`ing each file because it caused issues with nginx on the remote server accessing the files.
If you have any suggestion feel free to post it.
Thanks!
